#!/bin/bash
#
# GreenMind Installer for Raspberry Pi OS Lite
#

# Install Node-RED
if bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --confirm-install --confirm-pi --nodered-version="3.1.5" --node16 ; then
    echo "Node-RED installed, creating GreenMind folder"
else
    echo "Node-RED installation failed, check Node-RED log for more details"
    exit 1
fi

# Create GreenMind folder
if mkdir -p /home/pi/greenmind/ ; then
    echo "GreenMind folder created, downloading files"
else
    echo "Failed to create GreenMind folder, check permissions or reboot, exiting"
    exit 1
fi

# Download GreenMind files
cd /home/pi/greenmind/
if wget -O greenmind.json https://raw.githubusercontent.com/ThomasAndreini/GreenMind/master/greenmind.json ; then
    echo "greenmind.json downloaded, downloading modified settings.js"
else
    echo "Failed to download greenmind.json, check your internet connection, exiting"
    exit 1
fi

cd /home/pi/.node-red
if wget -O settings.js https://raw.githubusercontent.com/ThomasAndreini/GreenMind/master/installer/settings.js ; then
    echo "settings.js downloaded, downloading package.json"
else
    echo "Failed to download settings.js, check your internet connection, exiting"
    exit 1
fi

if wget -O package.json https://raw.githubusercontent.com/ThomasAndreini/GreenMind/master/package.json ; then
    echo "package.json downloaded, installing it"
else
    echo "Failed to download package.json, check your internet connection, exiting"
    exit 1
fi

# Install extra nodes
if npm install ; then
    echo "Extra nodes installed, GreenMind is installed successfully, starting Node-RED"
else
    echo "Can't install extra nodes, exiting"
    exit 1
fi

# Start Node-RED
node-red-start
